export const {
  PORT,
  NODE_ENV,
  DATABASE_URL,
  PORKBUN_TELEGRAM_TOKEN,
  TELEGRAM_BOT_TOKEN,
  SUPABASE_DATABASE_PASSWORD,
  TELEGRAM_USER_AWS_SECRET_KEY,
  TELEGRAM_USER_AWS_ACESS_KEY,
} = process.env;
