name: Deploy to EC2

on:
  workflow_dispatch:  # Triggered manually or by the first workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
          sudo docker pull manankansara0903/zapbot:latest
          sudo docker stop zapbot-container || true
          sudo docker rm zapbot-container || true
          sudo docker run -d --name zapbot-container -p 80:8080 manankansara0903/zapbot:latest
